# Generated by Django 4.1.7 on 2023-11-17 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0002_alter_visitas_fecharecordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fechaRecordatorio',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 22, 10, 25, 428584)),
        ),
    ]
