# Generated by Django 4.1.7 on 2023-11-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0003_alter_visitas_fecharecordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fechaRecordatorio',
            field=models.DateTimeField(),
        ),
    ]
