# Generated by Django 4.1.7 on 2023-11-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0004_alter_visitas_fecharecordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_Paciente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='idMedico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='idPaciente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_contactoEmergencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_seguroMedico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='id_paciente',
            field=models.CharField(max_length=50),
        ),
    ]
