# Generated by Django 4.1.7 on 2023-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0006_alter_paciente_numeroidentificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numeroIdentificacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='identifiacionUsuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rolUsuario',
            field=models.CharField(choices=[('Medico', 'Medico'), ('Enfermera', 'Enfermera'), ('Recursos Humanos', 'Recursos Humanos'), ('Administrativo', 'Administrativo')], max_length=50),
        ),
    ]
