# Generated by Django 4.1.7 on 2023-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0008_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fechaRecordatorio',
            field=models.DateTimeField(null=True),
        ),
    ]
